name: build

on: [push]

jobs:
  build:
    needs: version-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    name: Testing uoapi with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Ensure latest pip
        run: pip install --upgrade pip

      - name: Install dependencies and script
        run: pip install -r requirements.txt -r test-requirements.txt -e .

      # Skipping linting and type checking for now...
      # - name: Lint with flake8
      #   run: flake8
      # - name: Run static type analyzer
      #  run: mypy

      - name: Test with pytest
        run: pytest tests/
